Fix rendering GraphQL query input validation error (#556)
This was caught by TypeScript 4.4. It looks like we're expecting a
`ValidationError` from our internal `indie-api-types` library which has
`key` property. However, we're actually receiving a Runtypes
`ValidationError` which results in this zen message:

> ValidationError: undefined is invalid

This just dumps the full Runtypes validation error as part of the normal
Error handling.

Co-authored-by: Ryan Ling <ryan@outlook.com.au>